### ISSUE TITLE
Refresh of Active Windows causes freeze

### ISSUE THREAD

**Issue by AKruimink** [AKruimink/WinReform#25]
### _**Describe the bug**_
When the Active Window is being refreshed it freezes the ui temporarily.

### _**To Reproduce**_
1. Open the app
2. Enable auto refresh
3. Drag the window around

### _**Expected behavior**_
Preferaly the ui should be responsive, regardless of data updates

### _**Desktop (please complete the following information):**_
 - OS: Windows 10 Version 18363.1016
 - Version: Pre release

### _**Additional context**_
n/a

**Comment by Ylambers** [comment]
I guess the best way to tackle this problem is to make use of async.

**Comment by AKruimink** [comment]
@Ylambers  Thank you, that was indeed the idea, currently working on it. Hope to have it done somewhere within the next couple days!

**Comment by Ylambers** [comment]
I'm looking forward to see the solution you created!
